baseurl = "/"
languageCode = "zh-cn"
title = "HG's BLOG"
author = "Heaven Zone"
theme = "hgivy"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
canonifyurls = true
paginate = 800

[blackfriday]
    extensionsmask = ["noIntraEmphasis"]
    fractions= false

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "主页"
    url = "/"
    weight = 1
[[menu.main]]
    name = "我"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "分类"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 4
[[menu.main]]
    name = "订阅"
    url = "/index.xml"

[params]
    description = "Have Fun"
    footer = "&copy; [Heaven Zone](https://zhonghaoguang.com) 2018 | [Github](https://github.com/heavenzone) "

  highlightjsVersion = "9.12.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "python", "css"]
  highlightjsTheme = "github"
