---
title: "kylin-ubuntu安装R语言和Rstudio"
author: "Heaven Zone"
date: 2015-07-23T21:13:14-05:00
categories: ["R"]
tags: ["R", "rstudio", "ubuntu"]
---


## 前言

在本文你将会了解到**在ubuntu打造R语言开发环境的方法**。

主要使用的软件如下：

- Kylin-ubuntu麒麟系统：银河麒麟**社区版**：[下载](http://www.ubuntukylin.com/downloads/download.php?id=52)
- R语言版本：R version 3.4.1 (2017-06-30)，[官网](https://www.r-project.org/)
- Rstudio：开发版1.1.375 (当时1.1.xxx版本还没发布，看[最新版本](https://www.rstudio.com/products/rstudio/release-notes/))
- texlive2017：[下载texlive2017-20170524.iso](https://mirrors.tuna.tsinghua.edu.cn/CTAN/systems/texlive/Images/)
- 输入法：[小小输入法yong](http://yong.dgod.net) + ibus，[下载yong-lin-2.4.0-0.7z](http://ys-l.ys168.com/244626558/m3K3L3H7M3IOUjRgkjh/yong-lin-2.4.0-0.7z)



## 修改kylin-ubuntu的安装源

- 参考[这里：ubuntu.org.cn](http://wiki.ubuntu.org.cn/%E6%A8%A1%E6%9D%BF:17.04source)

中途输了一条这样的代码不知道有没有用

```
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 8D5A09DC9B929006
```

修改`sudo vim /etc/apt/sources.list`

把麒麟那几行用`#`注释掉

```bash
# deb file:///media/kylin/Kylin-4.0.2 juniper main
# deb http://cn.archive.ubuntu.com/ubuntu/ main univer multivers restricted
# deb http://archive.kylinos.cn/yhkylin/ juniper main restricted universe multiverse


deb http://cn.archive.ubuntu.com/ubuntu/ zesty main restricted universe multiverse
deb http://cn.archive.ubuntu.com/ubuntu/ zesty-security main restricted universe multiverse
deb http://cn.archive.ubuntu.com/ubuntu/ zesty-updates main restricted universe multiverse
deb http://cn.archive.ubuntu.com/ubuntu/ zesty-backports main restricted universe multiverse

# 源码
deb-src http://cn.archive.ubuntu.com/ubuntu/ zesty main restricted universe multiverse
deb-src http://cn.archive.ubuntu.com/ubuntu/ zesty-security main restricted universe multiverse
deb-src http://cn.archive.ubuntu.com/ubuntu/ zesty-updates main restricted universe multiverse
deb-src http://cn.archive.ubuntu.com/ubuntu/ zesty-backports main restricted universe multiverse

deb http://cn.archive.ubuntu.com/ubuntu/ trusty-backports main restricted universe
# rstudio源
deb http://cran.rstudio.com/bin/linux/ubuntu zesty/
```

然后输入下面代码更新软件列表

```
sudo apt-get update
```

## 安装yong输入法

搜狗输入法很好，终于有`大linux`系统版本了，可是在这里我们要使用**Rstudio**，基于Rstudio对fcitx输入法支持不是很友好，我们只好选择**ibus**输入法吧，非常幸运，我最喜欢的linux输入法**小小输入法：yong**可以完美嵌入ibus，如果你坚持要使用fcitx输入法，可以参考下面链接，看看有没有帮助，我尝试过，貌似没有成功**-_-!**

- [官网support上的一个讨论](https://support.rstudio.com/hc/en-us/articles/205605748-Using-RStudio-0-99-with-Fctix-on-Linux)
- [ Rstudio 不能切换中文输入（fctix） ](http://blog.csdn.net/qq_27755195/article/details/51002620)
- [RStudio无法切换中文输入法](http://bbs.pinggu.org/thread-4201324-1-1.html)
- [谁能够解决Linux下RStudio的fcitx输入不了中文](http://bbs.pinggu.org/thread-5936604-1-1.html?inifm=yes)

### 安装iBus框架

在终端输入以下命令安装ibus：

```shell
sudo apt-get install ibus ibus-clutter ibus-gtk ibus-gtk3 ibus-qt4
```
### 卸载fcitx
```
sudo apt-get remove fcitx
```

听说这里先安装ibus，再卸载fcitx，这个先后顺序是有必要的，否则会导致系统无法启动，幸好，我当时的安装顺序就是这个顺序，因此也没有遇到该问题。

### 安装yong小小输入法

参考官网说明：[点这里](http://yong.dgod.net/read.php?tid=6;fpage=2)

打开**下载**文件夹，双击文件`yong-lin-2.4.0-0.7z`，然后像windows下面操作一样把它解压到当前文件夹就可以了，然后执行以下命令：

```
cd ~/下载/yong
# 下面这句可不输入，如果yong-tool.sh没有可执行权限才运行这条语句
chmod a+x yong-tool.sh 
sudo ./yong-tool.sh –install
```

可以下载一个**ChmSee**软件来查看压缩包里面的帮助文档**yong.chm**，先安装一些依赖包：

```
sudo apt-get install libc6 libchm1 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk2.0-0 libpango1.0-0 libwebkitgtk-1.0-0 libxml2
```

下载libgcrypt11，[点这里下载](http://launchpadlibrarian.net/279485070/libgcrypt11_1.5.3-2ubuntu4.4_amd64.deb)

下载chmsee，[点此下载](http://kr.archive.ubuntu.com/ubuntu/pool/universe/c/chmsee/chmsee_1.3.0-2ubuntu2_amd64.deb)

输入下面代码手动安装：

```
sudo dpkg -i libgcrypt11_1.5.3-2ubuntu4.4_amd64.deb 
sudo dpkg -i chmsee_1.3.0-2ubuntu2_amd64.deb
```

### ibus配置添加yong

配置步骤：首选项->输入法->添加->汉语->Yong->添加，搞定。

切换输入法快捷键：首选项->常规->下一输入法->`...`，点这三个点进去设置自己舒服的快捷键吧，忘了默认快捷键是什么了，反正我用的是`Ctrl + Space`。

### 简单配置一下yong小小输入法

修改文件`~/.yong/yong.ini`：

```
[IM]
default=6
# 这里改为6，使用拼音输入法
```
另外在设置里面设置一下翻页键为`, .`。


## 安装R语言和Rstudio

- 参考：[CRAN](https://cran.rstudio.com/bin/linux/ubuntu/)
- 参考：[ubuntu系统上安装R包问题的解决办法](http://www.xuebuyuan.com/1234434.html)

### 安装R

```bash
sudo apt-get install r-base
```
### 安装Rstudio

安装R一句话就搞掂，貌似Rstudio并没有那么容易。

#### 添加rstudio安装源

实际上在上面步骤已经添加这个了，可以不需要做下面这行代码

```
# sudo echo "deb http://cran.rstudio.com/bin/linux/ubuntu zesty/" | sudo tee -a /etc/apt/sources.list
```

#### 导入密钥

实际上我还没弄懂后面那个key是怎么来的

```
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
gpg --keyserver keyserver.ubuntu.com --recv-key E084DAB9
gpg -a --export E084DAB9 | sudo apt-key add -
```



#### 安装Rstudio

先安装gdebi-core

```
sudo apt-get install gdebi-core
```

然后下载Rstudio，我下载的是rstudio-xenial-1.1.375-amd64.deb，这是到目前为止最新的测试版，有一些新特性，很不错，该文件下载下来在`~/下载`文件夹，输入下面命令安装：

```
cd ~/下载
sudo gdebi -n rstudio-xenial-1.1.375-amd64.deb
```

#### 简单配置rstudio

下面再对Rstudio做一些简单配置：

- /Tools/Global Options/Sweave，Weave Rnw files using:`knitr`
- /Tools/Global Options/Sweave，Typeset LaTeX into PDF using:`XeLaTeX`
- /Tools/Global Options/Packages/CRAN mirror，选择一个中国的镜像

#### 安装R的常用包

安装r的Cairo包前先在ubuntu终端安装两个库文件

```bash
sudo apt-get install libcairo2-dev libxt-dev
```

然后在rstudio安装Cairo包，下面代码在Rstudio的R命令行输入：

```
install.packages("Cairo")
```

安装XML包前，现在ubuntu安装libxml2-dev

```shell
sudo apt-get install libxml2-dev
```

然后在rstudio安装XML包，下面代码在Rstudio的R命令行输入：

```
install.packages("XML")
```


再安装一些经常用到的R包

```
install.packages("formatR")
install.packages("openxlsx")
install.packages("ggplot2")
install.packages("reshape2")
install.packages("bookdown")
install.packages("blogdown")
install.packages("rticles")
install.packages("bookdownplus")
install.packages("RSQLite")
install.packages("stringr")
```

## 安装texlive2017

- <http://www.latexstudio.net/archives/9788>
- <http://seisman.info/install-texlive-under-linux.html>
- <http://blog.163.com/wang_existed/blog/static/2095513002012620104911474/>

下载[texlive2017](http://mirrors.ustc.edu.cn/CTAN/systems/texlive/Images/texlive2017.iso)的iso，在win10里面解压了(当然也可以在ubuntu下下载texlive然后解压)，放进了u盘，把u盘插进麒麟系统，自动识别到了，终端进入u盘的texlive目录，输入`sudo ./install-tl`，不能启动安装。

该文件没有执行权限，输入`chmod a+x ./install-tl`尝试修改权限，未果，可能对u盘没有写权限。

查看`install-tl`，是个perl文档，那么就直接输入`sudo perl install-tl --gui`吧，发现出现`Cannot load Tk, maybe something is missing`错误，于是就要先安装`perl-tk`，于是就可以正常启动图形安装界面了，不修改安装选项，直接默认安装了（其实虽然出现错误提示，未能启动gui安装界面，但是也会在终端里面进入命令行的安装界面，应该按`i`就可以安装了，不过没试）。

#### 安装pandoc

安装pandoc，这个是在生成各种文件时会用到的，尤其是转换成pdf文件时。

```shell
sudo apt-get install pandoc
sudo apt-get install libdigest-perl-md5-perl perl-tk
sudo perl ./install-tl
```

#### 添加texlive环境变量

安装好texlive2017后，尝试knitr一个rmarkdown到pdf，提示错误：`pandoc: xelatex not found. xelatex is needed for pdf output.`，用pdflatex的时候也是出现错误`pandoc: pdflatex not found. pdflatex is needed for pdf output.`，估计是还没设置texlive的环境变量。

打开`~/.bashrc`添加下面环境变量：

```shell
# TeX Live 2017
export MANPATH=${MANPATH}:/usr/local/texlive/2017/texmf-dist/doc/man
export INFOPATH=${INFOPATH}:/usr/local/texlive/2017/texmf-dist/doc/info
export PATH=${PATH}:/usr/local/texlive/2017/bin/x86_64-linux
```

添加了上面的环境变量，在rstudio里面还是生成不了pdf文件，还是提示找不到xelatex或者pdflatex，在百度上基本找不到相关的文章，幸好找到一篇stackoverflow的文章，[点这里: 《Add TeX path to R Studio - Ubuntu》](https://stackoverflow.com/questions/30601171/add-tex-path-to-r-studio-ubuntu)

以下在rstudio操作：

```python
> Sys.which("xelatex")
xelatex 
     "" 
> Sys.which("pdflatex")
pdflatex 
      "" 
> Sys.getenv("PATH")
[1] "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
> 
```
可见texlive的相关目录并没有出现在R的环境变量PATH里面(会不会是因为先安装Rstudio然后再安装texlive造成的呢？)，rstudio就找不到xelatex和pdflatex，我已经在ubuntu终端测试了xelatex可以用，texlive2017安装没有问题。

最后发现`/etc/environment`文件和`Sys.getenv("PATH")`的输出是一样的，于是在`/etc/environment`文件内容PATH变量后面括号内添加以下代码：

```
:/usr/local/texlive/2017/bin/x86_64-linux
```

添加后，我输入`source /etc/environment`后，我重启Rstudio，输入`Sys.getenv("PATH")`，并没有显示添加后的代码，不过好在我重启ubuntu系统后，预期出现了添加的代码，并可以正常生成pdf文件了。

其实在修改`/etc/environment`之前，我是修改`Rprofile.site`文件来处理这个问题的，下面介绍一下修改Rprofile.site文件。

#### 修改Rprofile.site文件

这个步骤不是必须，但是了解Rprofile.site文件对使用Rstudio有很多好处，下面简单介绍。

这里主要参考了这两个链接：

- [Add TeX path to R Studio - Ubuntu](https://stackoverflow.com/questions/30601171/add-tex-path-to-r-studio-ubuntu)，我也在这里回复了楼主。
- [Customizing Startup](http://www.statmethods.net/interface/customizing.html)

下面在rstudio里面添加texlive的环境变量:

输入`sudo gedit /usr/lib/R/etc/Rprofile.site`修改Rprofile.site文件，我把下面语句添加到了First函数里面，当然放在外面应该也是可以的。

```
# 这一句是处理上一小节的问题的，这里可以不添加的
Sys.setenv(PATH=paste(Sys.getenv("PATH"),"/usr/local/texlive/2017/bin/x86_64-linux",sep=":"))

# 设置locale语言，设置成英语的好处是避免一些错误提示乱码
Sys.setlocale("LC_ALL","English")
```

你可以修改First函数和Last函数做一些有趣的东西，例如做一个不错的欢迎界面，或者每次启动Rstudio的时候自动帮你载入常用的包package。


## ubuntu其他一些软件的安装

### cmd markdown需要安装gconf2 

```
sudo apt-get install gconf2
```

下载cmd markdown解压就直接可以使用了。

### 安装flashplugin

1. 打开网页：http://get.adobe.com/flashplayer
2. 选择**tar.gz适用于linux**，点下载
3. 双击下载的文件解压

```shell
cd ~/下载/flash_player_npapi_linux.x86_64/
sudo cp -r usr/* /usr
sudo cp 下载/flash_player_npapi_linux.x86_64/libflashplayer.so /usr/lib/mozilla/plugins/
```

打开firefox的**Add-ons Manager**的**Plugins**，看到了**Shockwave Flash 27.0 r0**，说明已经成功加载了flash了。


### firefox安装这些addon

- gooreplacer
- Decentraleyes

切换同步服务器到国内服务器，参考这里：[切换同步服务器](https://zhidao.baidu.com/question/1113233119789701899.html)


### 安装微信electron

- 参考这里：[文档](https://github.com/electron/electron/blob/master/docs-translations/zh-CN/project/README.md)

```shell
sudo apt-get install npm
sudo apt-get install cnpm
sudo apt-get install git
sudo apt-get install nodejs-legacy
sudo cnpm install -g package --registry=https://registry.npm.taobao.org
git clone https://github.com/geeeeeeeeek/electronic-wechat.git
cd electronic-wechat
npm install && npm start
npm run build:linux
```



